###
# List of methods/modules and their dependencies:
###
modules:
    - name: common
    - name: uri_utils 
      depends: ['common']
    - name: edit_distance 
      depends: ['common']
    - name: anonymization 
      depends: ['common']
